(* size_t manifold_mesh_relation_barycentric_length(ManifoldMeshRelation *m); *)
(* ManifoldVec3 *manifold_mesh_relation_barycentric(void *mem, *)
(*                                                  ManifoldMeshRelation *m); *)
(* size_t manifold_mesh_relation_tri_bary_length(ManifoldMeshRelation *m); *)
(* ManifoldBaryRef *manifold_mesh_relation_tri_bary(void *mem, *)
(*                                                  ManifoldMeshRelation *m); *)
